// Controller tests with a DOM adapter. These are not visual/browser tests.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g)];
new Function(scripts.at(-1)[1]);
function setup(){const nodes=new Map();function el(s){if(!nodes.has(s))nodes.set(s,{textContent:'',innerHTML:'',value:'',hidden:false,classList:{toggle(){},add(){},remove(){}},addEventListener(){},setAttribute(){},removeAttribute(){},querySelectorAll(){return []},focus(){},showModal(){this.open=true},close(){this.open=false},click(){}});return nodes.get(s)}el('#meta').textContent=scripts[0][1];el('#initial').textContent=scripts[1][1];el('#dir-date').value='2026-10-03';const env={document:{getElementById:id=>el('#'+id),querySelector:el,addEventListener(){},createElement:()=>el('download-link'),body:{classList:{add(){},remove(){}}}},window:{addEventListener(){},print(){}},location:{hash:'#home',protocol:'file:'},setTimeout:()=>0,clearTimeout(){},console,Blob,URL,URLSearchParams,structuredClone,atob,Uint8Array,FormData,confirm:()=>true,fetch:()=>Promise.reject(Error('Offline'))};const context=vm.createContext(env);vm.runInContext(scripts.at(-1)[1],context);return {run:s=>vm.runInContext(s,context),el,env}}
(async()=>{const x=setup();let groups=0;assert(x.el('#view').innerHTML.includes('เริ่มต้นสำรวจข้อมูล'));groups++;
for(const page of ['home','directory','hierarchy','people','timeline','documents','modules','manage']){x.env.location.hash='#'+page;x.run('render()');assert(x.el('#view').innerHTML.length>100)}groups++;
assert.equal(x.run('META.packages.length'),23);assert.equal(x.run('META.models.length'),33);assert.equal(x.run('META.documents.filter(d=>d.kind==="Word").length'),9);assert.equal(x.run('META.workbook.length'),4);groups++;
assert.equal(x.run('state.organizations.length'),3);assert.equal(x.run('state.people.length'),2);assert.equal(x.run('state.assignments.length'),2);groups++;
assert.equal(x.run('localDirectory({at:"2026-04-01T00:00:00Z"}).entries[0].currentHolder'),'Synthetic Current Holder');assert.equal(x.run('localDirectory({at:"2025-07-01T00:00:00Z"}).entries[0].currentHolder'),'Synthetic Former Holder');assert.equal(x.run('localDirectory({at:"2026-04-01T00:00:00Z",q:"nomatch"}).total'),0);groups++;
assert.equal(x.run('esc("<img src=x onerror=alert(1)>")'),'&lt;img src=x onerror=alert(1)&gt;');assert.equal(x.run('localDirectory({at:"2026-04-01T00:00:00Z",pageSize:1,page:2}).entries.length'),0);groups++;
x.env.location.hash='#hierarchy';x.run('render()');assert(x.el('#org-content').innerHTML.includes('Synthetic Central Sangha Unit'));x.el('#org-search').value='EXAM';x.run('showHierarchy()');assert(x.el('#org-content').innerHTML.includes('Synthetic Exam Centre'));groups++;
x.env.location.hash='#timeline';x.run('render()');x.el('#timeline-date').value='2026-05-01';x.run('showTimeline()');assert(x.el('#timeline-content').innerHTML.includes('Synthetic Person Appointed'));assert(!x.el('#timeline-content').innerHTML.includes('Synthetic Person Acting'));groups++;
x.env.location.hash='#documents';x.run('render()');x.el('#doc-query').value='Project Charter';x.el('#doc-kind').value='Word';x.run('showDocs()');assert(x.el('#doc-list').innerHTML.includes('Project_Charter'));groups++;
for(const a of x.run('META.attachments')){const bytes=Buffer.from(a.base64,'base64');assert(bytes.subarray(0,2).toString()==='PK');const original=fs.readFileSync(path.join(__dirname,'source_files',a.name));assert(bytes.equals(original))}groups++;
console.log(`${groups} frontend controller checks passed (DOM adapter; not a browser visual test).`)
})().catch(e=>{console.error(e);process.exitCode=1});
