import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { startPortal } from './server.mjs';

async function setup(t){const temp=await fs.mkdtemp(path.join(os.tmpdir(),'sangha-portal-test-')),dataFile=path.join(temp,'state.json');const app=await startPortal({port:0,dataFile});t.after(async()=>{await app.close();await fs.rm(temp,{recursive:true,force:true})});const base=`http://127.0.0.1:${app.port}`;return {app,base,dataFile,request:(url,opt={})=>fetch(base+url,opt)}}
async function login(env){const r=await env.request('/api/login',{method:'POST',headers:{Origin:env.base,'Content-Type':'application/json'},body:JSON.stringify({code:env.app.accessCode})});assert.equal(r.status,200);const session=await r.json();const cookie=r.headers.get('set-cookie').split(';')[0];return {Cookie:cookie,Origin:env.base,'Content-Type':'application/json','X-CSRF-Token':session.csrf}}
async function mutate(env,headers,revision,operation,input){return env.request('/api/admin/mutate',{method:'POST',headers,body:JSON.stringify({revision,operation,input})})}

test('HTML and public directory call baseline projection; no private fields',async t=>{const env=await setup(t);const home=await env.request('/');assert.equal(home.status,200);assert((await home.text()).includes('ระบบฐานข้อมูลคณะสงฆ์และการศึกษา'));const r=await env.request('/api/public/directory?asOf=2026-03-01T00:00:00Z&q=current');assert.equal(r.status,200);const data=await r.json();assert.equal(data.entries[0].currentHolder,'Synthetic Current Holder');assert.deepEqual(Object.keys(data.entries[0]).sort(),['currentHolder','organizationName','organizationType','positionTitle','publicEntryId']);assert(!JSON.stringify(data).includes('PRIVATE'));const previous=await (await env.request('/api/public/directory?asOf=2025-07-01T00:00:00Z')).json();assert.equal(previous.entries[0].currentHolder,'Synthetic Former Holder')});
test('session login, bad code, CSRF, logout and restricted source files',async t=>{const env=await setup(t);assert.equal((await env.request('/api/admin/data')).status,401);assert.equal((await env.request('/api/login',{method:'POST',headers:{Origin:env.base,'Content-Type':'application/json'},body:'{"code":"wrong"}'})).status,401);const headers=await login(env);assert.equal((await env.request('/api/admin/data',{headers})).status,200);const bad={...headers,'X-CSRF-Token':'wrong'};assert.equal((await mutate(env,bad,0,'people:create',{displayName:'Synthetic Test',isSynthetic:true})).status,403);assert.equal((await mutate(env,{...headers,Origin:'https://example.com'},0,'people:create',{isSynthetic:true})).status,403);for(const p of ['/server.mjs','/data/portal-state.json','/baseline/prisma/seed.ts'])assert.equal((await env.request(p)).status,404);assert.equal((await env.request('/api/logout',{method:'POST',headers,body:'{}'})).status,200);assert.equal((await env.request('/api/admin/data',{headers})).status,401)});
test('organization and person writes persist, revision conflict and rollback',async t=>{const env=await setup(t),headers=await login(env);let state=await (await env.request('/api/admin/data',{headers})).json();let r=await mutate(env,headers,state.revision,'org:create',{code:'SYN-NEW',displayName:'Synthetic New Office',type:'SANGHA_UNIT',parentId:state.organizations[0].id,isSynthetic:true});assert.equal(r.status,200);state=await r.json();assert.equal(state.organizations.length,4);assert.equal(state.orgHistory.length,1);assert.equal(state.audit.length,1);assert.equal((await mutate(env,headers,0,'people:create',{displayName:'Synthetic Invalid Revision',isSynthetic:true})).status,409);r=await mutate(env,headers,state.revision,'people:create',{displayName:'Synthetic New Person',isSynthetic:true});assert.equal(r.status,200);state=await r.json();assert.equal(state.people.length,3);assert.equal((await mutate(env,headers,state.revision,'people:create',{displayName:'Person',isSynthetic:false})).status,400);assert.equal((await mutate(env,headers,state.revision,'org:create',{code:'SYN-BAD',displayName:'Synthetic Bad',type:'EXAMINATION_UNIT',parentId:state.organizations[0].id,isSynthetic:true})).status,400);const saved=JSON.parse(await fs.readFile(env.dataFile,'utf8'));assert.equal(saved.revision,2);assert.equal(saved.organizations.length,4);const restarted=await startPortal({port:0,dataFile:env.dataFile});t.after(()=>restarted.close());const r2=await fetch(`http://127.0.0.1:${restarted.port}/api/session`);assert.equal((await r2.json()).authenticated,false);assert.equal(saved.people.at(-1).displayName,'Synthetic New Person')});
test('reparent uses cycle prevention and preserves previous history',async t=>{const env=await setup(t),headers=await login(env);const initial=await (await env.request('/api/admin/data',{headers})).json();const [root,edu,exam]=initial.organizations;const cycle=await mutate(env,headers,0,'org:reparent',{id:root.id,parentId:exam.id,reason:'Synthetic cycle test',isSynthetic:true});assert.equal(cycle.status,400);const ok=await mutate(env,headers,0,'org:reparent',{id:exam.id,parentId:edu.id,reason:'Synthetic correction',isSynthetic:true});assert.equal(ok.status,200);const saved=await ok.json();assert.equal(saved.orgHistory[0].previousParentId,edu.id);assert.equal(saved.orgHistory[0].reason,'Synthetic correction')});
test('timeline validates overlap and explicit publication becomes searchable',async t=>{const env=await setup(t),headers=await login(env);let state=await (await env.request('/api/admin/data',{headers})).json();const pos=state.positionDefinitions[0],person=state.people[0];const input={organizationId:pos.organizationId,title:pos.title,personId:person.id,state:'APPOINTED',effectiveFrom:'2026-02-15T00:00:00Z',effectiveTo:'2026-03-01T00:00:00Z',documentRecordId:'SYN-DOC-NEW',isSynthetic:true};assert.equal((await mutate(env,headers,0,'assignment:add',input)).status,400);input.effectiveFrom='2026-07-01T00:00:00Z';input.effectiveTo=null;let r=await mutate(env,headers,0,'assignment:add',input);assert.equal(r.status,200);state=await r.json();assert.equal(state.assignments.length,3);assert.equal(state.assignmentEvents.length,1);let publicRows=await (await env.request('/api/public/directory?q=Synthetic%20Person')).json();assert.equal(publicRows.total,0);r=await mutate(env,headers,state.revision,'directory:publish',{isSynthetic:true});assert.equal(r.status,200);state=await r.json();publicRows=await (await env.request('/api/public/directory?q=Synthetic%20Person&asOf=2026-10-03T00:00:00Z')).json();assert.equal(publicRows.total,1);assert.equal(publicRows.entries[0].currentHolder,person.displayName);assert.equal(state.audit.length,2);assert.equal((await env.request('/api/public/directory?asOf=bad')).status,400)});
test('public endpoint enforces rate limit',async t=>{const env=await setup(t);let r;for(let i=0;i<31;i++)r=await env.request('/api/public/directory');assert.equal(r.status,429);assert(r.headers.get('retry-after'))});
